---
title: "ravi workspace"
author: "Ravi Patel"
date: "April 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2)

nba <- read.csv("nba_games_stats.csv")
season_stats <- read.csv('Seasons_Stats.csv')
players <- read.csv('Players.csv')
player_data <- read.csv('player_data.csv')
```


```{r}
teams <- nba %>%
  group_by(Team) %>%
  summarize(
    steals = mean(Steals)
  )
```

```{r}
years1 <- all_data
years1$X3P.[is.na(years1$X3P.)] <- 0
years1 <- na.omit(all_data)

years1 <- separate(years1, Pos.y, into=c("position", "alt_position"), sep="-")
```


```{r}
years2 <- years1 %>%
  group_by(season_start) %>%
  summarize(
    PTS = mean(PTS),
    AST = mean(AST.),
    TRB = mean(TRB.),
    STL = mean(STL.),
    BLK = mean(BLK.),
    FG = mean(FG.),
    X3P = mean(X3P.),
    X3PA = mean(X3PA),
    FT = mean(FT.)
  )
```

```{r}
ggplot(years2, aes(x=season_start, y=PTS)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=AST)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=TRB)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=STL)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=BLK)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=FG)) +
  geom_point() +
  labs(
    title = "Field Goal Percentage by Year",
    x = "Year",
    y = "Field Goal Percentage"
  ) +
  scale_y_continuous(limits=c(0.415, 0.465)) +
  geom_line()
```
```{r}
ggplot(years2, aes(x=season_start, y=X3P)) + geom_point()
```
```{r}
ggplot(years2, aes(x=season_start, y=FT)) + geom_point()
```

```{r}
ggplot(years2, aes(x=season_start, y=X3PA)) + geom_point()
```


```{r}
body <- years1 %>%
  group_by(Player) %>%
  summarise(
    height = mean(height.y),
    weight = mean(weight.y),
    position = dplyr::first(position)
  )
```

```{r}
body[ , "height"] <- body[ , "height"] * 0.39370
body[ , "weight"] <- body[ , "weight"] * 2.20462
body <- separate(body, position, into=c("position", "alt_position"), sep="-")

```

```{r}
ggplot(body, aes(x=position, y=weight, fill=position)) + 
  geom_boxplot() +
  labs(
    title = "Body Weight by Position",
    x = "Position",
    y = "Weight in Pounds"
  )
```


```{r}
ggplot(body, aes(x=position, y=height, fill=position)) + 
  geom_boxplot() +
  labs(
    title = "Body Height by Position",
    x = "Position",
    y = "Height in Inches"
  )
```

```{r}
stretch <- years1 %>%
  group_by(season_start, position) %>%
  summarise(
    three = mean(X3PA)
  )
```

```{r}
ggplot(stretch, aes(x=season_start, y=three, color=position)) + 
  geom_line() +
  geom_point() +
  labs(
    title = "3-Point Attempts over the Years by Position",
    x = "Year",
    y = "3-Point Attempts",
    color = "Position"
  )
```

```{r}
years3 <- years1 %>%
  group_by(season_start) %>%
  summarize(
    FG = mean(FG.),
    X3P = mean(X3P.),
  ) 
```

```{r}
melted <- melt(years3, id.var="season_start")
```

```{r}
ggplot(melted, aes(x=season_start, y=value, color=variable)) + 
  geom_point() +
  geom_line() +
  labs(
    title = "Key Stats over the Years",
    x = "Year",
    y = "Percent",
    color = "Statistic"
  )
```

